### PR TITLE
Add ability to use imperial units

### PR DESCRIPTION
**Pull request by aaronblondeau**
Thanks for this great plugin!  I added the ability to support imperial units for a US based project I was working on.  The grunt build mangled things in the repo a bit so it might be easier to copy and paste changes from L.Control.Elevation.js manually rather than using a pull?

### CODE REVIEW

**Comment by MrMufflon** [comment]
Thanks, I will review it when I can find some time.

**Comment by jimmyangel** [comment]
I tested this change and noticed two problems: 1) Elevation says ft but it is still showing the same numbers as in metric, 2) the little line that attaches to the trail to indicate elevation is gone when I use the "imperial" option.

Here it is in metric:
image

And here in imperial (notice same height number and height indicator line gone):
image

Thanks

**Comment by jimmyangel** [comment]
Hi All, I went ahead and fixed the issue. Feel free to review it in my fork https://github.com/jimmyangel/Leaflet.Elevation/commit/754179964e8255bb14ff5422e99dd64970af863c

Let me know if you want me to start a pull request.

Thanks

**Comment by MrMufflon** [comment]
Done. Thanks for your work guys!

**Pull request merged**
